services:
  proxmox:
    hostname: pve
    image: dockurr/proxmox
    container_name: proxmox
    environment:
      PASSWORD: "root"
    ports:
      - 8006:8006
    volumes:
      - ./config:/etc/pve
      - ./storage:/var/lib/vz    
      - /var/run/docker.sock:/var/run/docker.sock      
    privileged: true
    restart: on-failure
    stop_grace_period: 1m
